---
# cloud_controller_uri: api.vcap.me
service:
  name: terracotta
  version: "3.7.5"
  description: 'Terracotta distributed cache service'
  plans: ['free']
  default_plan: free
  tags: ['terracotta', 'terracotta-3.7.5', 'distributed', 'cache']
  timeout: 20
ip_route: localhost
index: 0
token: changeterracottatoken
logging:
  level: debug
mbus: nats://localhost:4222
pid: /var/vcap/sys/run/terracotta_service.pid
node_timeout: 20
# z_interval: 30
# check_orphan_interval: 3600
# double_check_orphan_interval: 300
